import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarContainer from "@/components/main/sidebarcontainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <SidebarContainer />
        </div>
        <div className="md:ml-[300px] md:mt-14 mt-20 p-4 md:p-0">
          {children}
        </div>
      </body>
    </html>
  );
}
